version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fyp_user
      POSTGRES_PASSWORD: fyp_password
      POSTGRES_DB: fyp_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro
      - ./database/insert_begin.sql:/docker-entrypoint-initdb.d/insert_begin.sql:ro
      - ./database/insert_districts.sql:/docker-entrypoint-initdb.d/insert_districts.sql:ro
volumes:
  db_data:
